---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: disable selinux
  action: shell echo 0 >/selinux/enforce

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables
