- name: "git clone Cloudstack"
  git: repo="https://github.com/apache/cloudstack.git" version="4.3" dest=/opt/cloudstack
  tags:
    - clone

- name: 'to build Cloudstack mysqld needs to be up'
  service: name=mysqld state=started

- name: "copy build script marvin.sh"
  copy: src=roles/cloudstack/templates/marvin.sh dest=/opt/cloudstack/marvin.sh owner=root mode=755
  tags:
    - build

- name: "copy start script bootstrap.sh"
  copy: src=roles/cloudstack/templates/bootstrap.sh dest=/opt/cloudstack/bootstrap.sh owner=root mode=755
  tags:
    - start
    - build
    
- name: "Run marvin.sh"
  shell: /opt/cloudstack/marvin.sh
  tags:
    - build
    
- name: "copy start script bootstrap.sh"
  copy: src=roles/cloudstack/templates/bootstrap.sh dest=/opt/cloudstack/bootstrap.sh owner=root mode=755
  tags:
    - start
    
- name: "bootstrap the CloudStack Simulator"
  shell: /opt/cloudstack/bootstrap.sh
  tags:
    - start
